use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :phoenix_events_live, PhoenixEventsLiveWeb.Endpoint,
  url: [host: System.get_env("PHX_URL"), port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :phoenix_events_live, PhoenixEventsLive.Repo,
       adapter: Ecto.Adapters.Postgres,
       username: System.get_env("PGUSER"),
       password: System.get_env("PGPASSWORD"),
       database: System.get_env("PGDATABASE"),
       hostname: System.get_env("PGHOST"),
       port: System.get_env("PGPORT"),
       pool_size: String.to_integer(System.get_env("PGPOOLSIZE") || "10")

# Guardian config
config :phoenix_events_live, PhoenixEventsLive.Guardian,
       issuer: "dding_conference_app",
       secret_key: System.get_env("PHX_GUARDIAN_SECRET_KEY")

config :phoenix_events_live, PhoenixEventsLiveWeb.Endpoint,
       http: [:inet6, port: String.to_integer(System.get_env("PHX_PORT") || "4000")],
       secret_key_base: System.get_env("PHX_SECRET_KEY_BASE")

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :phoenix_events_live, PhoenixEventsLiveWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         :inet6,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :phoenix_events_live, PhoenixEventsLiveWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases (Elixir v1.9+)
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start each relevant endpoint:
#
#     config :phoenix_events_live, PhoenixEventsLiveWeb.Endpoint, server: true
#
# Then you can assemble a release by calling `mix release`.
# See `mix help release` for more information.
